config/routes.rb
Rails.application.routes.draw do
  

  resources :tests
  resources :tests
	get 'signup', to: 'users#new', as: 'signup'
	get 'login', to: 'sessions#new', as: 'login'
	get 'logout', to: 'sessions#destroy', as: 'logout'

	get "jobs/submit_customer"

 get 'home/index'
resources :jobs
  resources :users
  resources :sessions
  root 'sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

before_filter :authenticate 

def authenticate
  redirect_to "localhost:3000" unless current_user.present?
end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    respond_to do |format|
      if @job.save
        format.html { redirect_to jobs_path }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    @job = Job.where("job_id = ?",params[:customer])
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:customer, :project, :hours, :description, :date, :userid)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(job) do |f| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <% @jobers = Job.all %>

    <% @array_customers = Array.new() %>
    <% @count_customers = 0 %>

    <% @jobers.each do |j| %>
    <% @array_customers.insert(@count_customers,j.customer) %>
    <% @count_customers += 1 %>
    <% end %>

    <% @array_customers = @array_customers.uniq %>

    <% @array_customers.reject!(&:empty?) %>



    <% @array_projects = Array.new() %>
    <% @count_projects = 0 %>

    <% @jobers.each do |l| %>
    <% @array_projects.insert(@count_projects,l.project) %>
    <% @count_projects += 1 %>
    <% end %>

    <% @array_projects = @array_projects.uniq %>

    <% @array_projects.reject!(&:empty?) %>


    <div class="field" id="cust-tag">
    <%= f.label :Customer %>
    </div>
    <div class="field" id="cust-box">
    <%= f.select :customer,options_for_select((@array_customers.each).map {|i| [i,i] }),:'data-remote' => 'true', :'data-url' => url_for(:controller => 'jobs', :action => 'submit_customer', format: 'js') %>
    </div>

    <div class="field" id="project-tag">
    <%= f.label :Project %>
    </div>
    <div class="field" id="project-box">
    <%= f.select :project,options_for_select((@array_projects.each).map {|i| [i,i] }),:'data-remote' => 'true', :'data-url' => url_for(:controller => 'jobs', :action => 'submit_customer', format: 'js') %>
    </div>

    <div class="field" id="hours-tag">
    <%= f.label :Hours %>
    </div>
    <div class="field" id="hours-box">
    <%= f.number_field :hours,:class=>'text_field',:step=>'any' %>
    </div>

    <div class="field" id="description-tag">
    <%= f.label :Description %>
    </div>
    <div class="field" id="description-box">
    <%= f.text_field :description %>
    </div>
    <%-# this seems like an awful way of doing it but shouldnt cause any errors or anything(hiding date_field) -%>
     <div class="field" id="date-box">
    <%= f.date_field :date,:value => @date,style: "#{'display:none'}" %>
    </div>   

    <% @userid = User.all %>
    <div class="field" id="date-box">
     <%= f.select :userid,options_for_select((@userid.each).map {|i| [i.email,i.email] }),:'data-remote' => 'true', :'data-url' => url_for(:controller => 'jobs', :action => 'submit_customer', format: 'js') %>
    </div>  

    <div id="submit-button">
    <%= f.submit "Add Job" %>
    </div>


<% end %>

app/views/jobs/_table.html.erb
<div id="job-table">
<table class="table">
<thead class="bg-primary">
<tr>
	<th>Customer</th>
	<th>Project</th>
	<th>Hours</th>
	<th>Description</th>
	<th>Date</th>	
	<th>User</th>
	<th></th>
	<th></th>
</tr>
</thead>
<% @jobloop = Job.where(date: @date) %>
	<% @jobloop.each do |u| %>
		<tr class="bg-info">
			<td class="col-md-2"><div style="height: 28.49px;"><%= u.customer %></div></td>
			<td class="col-md-2"><%= u.project %></td>
			<td class="col-md-2"><%= u.hours %></td>
			<td class="col-md-2"><%= u.description %></td>
			<td class="col-md-2"><%= u.date %></td>
			<td class="col-md-2"><%= u.userid %></td>
			<td class="col-md-2"><%= link_to 'Edit', edit_job_path(u) %></td>
        	<td class="col-md-2"><%= link_to 'Destroy', u, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        	</tr>
	<% end %>
</table>
</div>

app/views/jobs/_table_admin.html.erb
<%= form_for(Job.new) do |f| %>
  <% if Job.new.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% Job.new.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



<%= f.date_field :date,:value => '06/30/2016 00:00',style: "#{'display:none'}" %>
<%= f.text_field :project,:value => ' ',style: "#{'display:none'}" %>
<%= f.number_field :hours,:value => 0,:class=>'text_field',:step=>'any',style: "#{'display:none'}" %>

<table class="table">
<thead class="bg-success">
<tr>
	<th width="8px">Customer <%= f.text_field :customer %><%= f.submit "Add Customer" %></th> 
	<th></th>  
</tr>
</thead>
<% @test_for_job_count = 0 %>
<% @jobloop = Job.all %>




<% #--creates new hash,fills hash with values,searches for dupes,print values/delete dupes %>
<% h = Hash.new(0) %>
<% @jobloop.each do |p| %>
<% if [p.customer].each{ |e| h[e] += 1 } %>
<% end %>
<% end %>
<% #----------------------# %>

	<% @jobloop.each do |u| %>
		<tr class="bg-info">
			<% if h[u.customer] == 1 %>
			<td class="col-md-3"><%= link_to u.customer,job_path(u)%></td>
			<td></td>
			<% end %>
			<% if h[u.customer] > 1 %>
			<td class="col-md-3"><%= link_to u.customer,job_path(u)%></td>
			<td></td>
			<% h.delete(u.customer) %>
			<% end %>
		</tr>
	<% end %>



</table>

<table class="table">
<thead class="bg-success">
<th>Projects <%= f.text_field :project %><%= f.submit "Add Project" %></th>	
</thead>


</table>


<table class="table">
<thead class="bg-success">
<th>Users (<%= link_to "Add User", signup_path %>)</th>

</thead>
<% @test = User.all %>

<% @test.each do |y| %>
<tr class="bg-info"><td><%= y.email %></td></tr>
<% end %>


</table>



<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<div id="title">
<h1>Admin Page</h1>
</div>

<%= render "jobs/table_admin"%>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<%= form_for(Job.new) do |f| %>
  <% if Job.new.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% Job.new.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div id="title">
<h1>Admin Page</h1>
</div>

<%= f.date_field :date,:value => '06/30/2016 00:00',style: "#{'display:none'}" %>
<%= f.text_field :project,:value => ' ',style: "#{'display:none'}" %>
<%= f.number_field :hours,:value => 0,:class=>'text_field',:step=>'any',style: "#{'display:none'}" %>

<table class="table">
<thead class="bg-success">
<tr>
	<th width="8px">Customer <%= f.text_field :customer %><%= f.submit "Add Customer" %></th>   
	<th></th>
</tr>
</thead>
<% @test_for_job_count = 0 %>
<% @jobloop = Job.all %>




<% #--creates new hash,fills hash with values,searches for dupes,print values/delete dupes %>
<% h = Hash.new(0) %>
<% @jobloop.each do |p| %>
<% if [p.customer].each{ |e| h[e] += 1 } %>
<% end %>
<% end %>
<% #----------------------# %>

	<% @jobloop.each do |u| %>
		<tr class="bg-info">
			<% if h[u.customer] == 1 %>
			<td class="col-md-3"><%= link_to u.customer,job_path(u)%></td>
			<td></td>
			<% end %>
			<% if h[u.customer] > 1 %>
			<td class="col-md-3"><%= link_to u.customer,job_path(u)%></td>
			<td></td>
			<% h.delete(u.customer) %>
			<% end %>
		</tr>
	<% end %>



</table>

<table class="table">
<thead class = "bg-success">
<th>Projects <%= f.text_field :project %><%= f.submit "Add Project" %></th>
</thead>

<% @jobloop.each do |u| %>

<% if u.customer == @job.customer %>
<tr class="bg-info"><td><%= u.project %></td></tr>
<% end %>


<% end %>


</table>

<table class="table">
<thead class="bg-success">
<th>Users</th>
</thead>
<% @test = User.all %>

<% @test.each do |y| %>
<tr class="bg-info"><td><%= y.email %></td></tr>
<% end %>


</table>



<% end %>