config/routes.rb
Rails.application.routes.draw do
  

  resources :tests
  resources :tests
	get 'signup', to: 'users#new', as: 'signup'
	get 'login', to: 'sessions#new', as: 'login'
	get 'logout', to: 'sessions#destroy', as: 'logout'

	get "jobs/submit_customer"

 get 'home/index'
resources :jobs
  resources :users
  resources :sessions
  root 'sessions#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

    <title>Timetrack</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

 
  		<div id="user_header">
  			<% if current_user %>
          Logged in as <%= current_user.email %><br />
          <%= link_to "Log Out", logout_path %>
        <% end %>

  		</div>
      <% if current_page?(home_index_path) %>
      <%= link_to "admin page", jobs_path %>  <br />
      <%= link_to "reports page", tests_path %>       
      <% elsif current_page?(root_path) %>
      <% #no links in login page #%>
      <%= link_to "Add User", signup_path %>
      <% elsif current_page?(jobs_path) %>
      <%= link_to "home page", home_index_path %> <br /> 
      <%= link_to "reports page", tests_path %>  
      <% elsif %>
      <%= link_to "home page", home_index_path %> <br /> 
      <%= link_to "admin page", jobs_path %>  <br />
      <% else %>
      <%= link_to "home page", home_index_path %> <br /> 
      <%= link_to "admin page", jobs_path %>  <br />       
      <%= link_to "reports page", tests_path %>    
      <% end %>

  		<% flash.each do |name,msg| %>
  			<%= content_tag :div, msg, id: "flash_#{name}" %>
  		<% end %>

    	<%= yield %>
 
<style type="text/css">
   body { background: #6699ff !important; } /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
</style>